# File required to load packs as Forge mods.
# Find more information on toml format v0.5.0 here:  https://github.com/toml-lang/toml

# Forge settings, don't touch!
modLoader="javafml"
loaderVersion="[36,)"

# The license for your pack. This is mandatory metadata and allows for easier comprehension of your redistributive properties.
# Review your options at https://choosealicense.com/. All rights reserved is the default copyright stance, and is thus the default here.
license="The Unlicense"

[[mods]] 
# The ID of your pack.
modId="gerwarpack"
# Version number.  Must start with a number or Forge complains.
version="5"
 # Display name for the pack in the in-game mods list.
displayName="GerWar pack"
# A URL for the "homepage" for this pack, displayed in the mod UI.
displayURL="https://discord.gg/nFarBdjmcJ"
# Pack logo.
logoFile="vingette.png"
# The description text for the pack (multi line!)
description='''
Vehicle pack for GerWar server. All files are from: lindqvist, LAV, MTS Official pack.
'''

[[dependencies.gerwarpack]]
    modId="mts"
    mandatory=true
    versionRange="[22.6.0,)"
    ordering="NONE"
    side="BOTH"
